#!/bin/bash

# Get the operating system name
os=$(uname -s)


# ----------------------------------------------------------------------- #
# ----------------------------------------------------------------------- #
# MACOS #
# ----------------------------------------------------------------------- #
# ----------------------------------------------------------------------- #
if [[ "$os" == "Darwin" ]]; then

  if [[ $(command -v brew) == "" ]]; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> /Users/hemroda/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    echo "Install Packages using Homebrew"

    brew tap homebrew/core
    brew tap hashicorp/tap
    brew install alacritty
    brew install jesseduffield/lazydocker/lazydocker
    brew install asdf
    brew install coreutils
    brew install docker-compose
    brew install lazydocker
    brew install libvips
    brew install libyaml
    brew install neovim
    brew install postgresql@14
    brew install redis
    brew install ripgrep
    brew install starship
    brew install stow
    brew install tree
    brew install hashicorp/tap/terraform
    brew install vlc
    brew install xz
    brew install yarn
    brew install Zellij
    brew install zola
    brew install --cask brave-browser
    brew install --cask discord
    brew install --cask docker
    brew install --cask firefox
    brew install --cask firefox@developer-edition
    brew install --cask flux
    brew install --cask font-fira-mono-nerd-font
    brew install --cask google-chrome
    brew install --cask ghostty
    brew install --cask iterm2
    brew install --cask messenger
    brew install --cask obsidian
    brew install --cask proton-drive
    brew install --cask proton-pass
    brew install --cask protonvpn
    brew install --cask signal
    brew install --cask spotify
    brew install --cask telegram
    brew install --cask vscodium
    brew install --cask whatsapp
  fi

  curl -LsSf https://astral.sh/uv/install.sh | sh
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi

echo "Preparing folders"
echo "..."
mkdir ~/Sites

echo "Use Stow to link files"
stow bash
stow config
stow git
stow languages
stow shared
stow ssh
stow vim
stow vscodium
rm ~/.zshrc
stow zsh

# Install Golang
asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
asdf install golang 1.24.0
asdf global golang 1.24.0

# Install NodeJS, Python, Ruby using ASDF
asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
asdf install nodejs 22.14.0
asdf global nodejs 22.14.0

asdf plugin add python https://github.com/asdf-community/asdf-python.git
asdf install python 3.13.4
asdf global python 3.13.4

asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
asdf install ruby 3.4.3
asdf global ruby 3.4.3

brew services start redis
brew services start postgresql

# Docker daemon on macOS without Docker Desktop
brew services start colima

# Include Rust's Cargo in your shell
. "$HOME/.cargo/env"
