tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-fonts"

brew "fzf"
brew "ripgrep"
brew "starship"
brew "nvm"
brew "postgresql", restart_service: true
brew "git"
brew "grep"
brew "ripgrep"
brew "wget"

cask "alacritty"
cask "flux"
cask "vlc"
cask "obs"
cask "whatsapp"
cask "telegram-desktop"
cask "obsidian"
cask "discord"
cask "docker"
cask "slack"
cask "postman"
cask "visual-studio-code"
cask "google-chrome"
cask "brave-browser"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "font-jetbrains-mono-nerd-font"
