font:
  normal:
    family: font-hack-nerd-font
    style: Regular

  bold:
    style: Bold

  italic:
    style: Italic

  bold_italic:
    style: Bold Italic

  size: 11


# Window padding (changes require restart)
#
# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
window:
  padding:
    x: 6
    y: 6
